version: '3.7'
services:
  frontend:
    build:
      context: ./frontend
    container_name: api-head-loss-frontend
    volumes:
      - ./frontend:/app/
      - /app/node_modules
    ports:
      - '3000:3000'
  backend:
    build:
      context: ./backend
    container_name: api-head-loss-backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/usr/src/app
    # depends_on:
    #   - frontend
  mailhog: # service for faking a SMTP server
    image: mailhog/mailhog
    ports:
      - '1025:1025' # smtp server
      - '8025:8025' # web ui
