version: '3.7'

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: headloss@10
      POSTGRES_USER: headloss
      POSTGRES_DB: headloss
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data/
  backend:
    build:
      context: ./reynolds-number-calculator
    environment:
      SQL_HOST: db
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./reynolds-number-calculator:/usr/src/app
    depends_on:
      - db
  mailhog: # service for faking a SMTP server
    image: mailhog/mailhog
    ports:
      - '1025:1025' # smtp server
      - '8025:8025' # web ui

volumes:
  db_data:
