# Generated by Django 3.2.2 on 2021-05-20 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0005_auto_20210513_2134"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="head_loss",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="analysis",
            name="material_condition",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="analysis",
            name="pipe_length",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="analysis",
            name="pipe_material",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
