# Generated by Django 3.2.2 on 2021-05-20 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0007_auto_20210520_0259"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysis",
            name="analysis_name",
            field=models.CharField(max_length=255, verbose_name="analysis name"),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="density",
            field=models.FloatField(blank=True, null=True, verbose_name="density"),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="head_loss",
            field=models.FloatField(blank=True, null=True, verbose_name="head loss"),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="kinematic_viscosity",
            field=models.FloatField(
                blank=True, null=True, verbose_name="kinematic viscosity"
            ),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="material_condition",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="material condition"
            ),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="pipe_diameter",
            field=models.FloatField(
                blank=True, null=True, verbose_name="pipe diameter"
            ),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="pipe_length",
            field=models.FloatField(blank=True, null=True, verbose_name="pipe length"),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="pipe_material",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="pipe material"
            ),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="volumetric_flow_rate",
            field=models.FloatField(
                blank=True, null=True, verbose_name="volumetric flow rate"
            ),
        ),
    ]
