# Generated by Django 3.2.2 on 2021-05-20 03:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0008_auto_20210520_0302"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysis",
            name="density",
            field=models.FloatField(default=0, verbose_name="density"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="analysis",
            name="kinematic_viscosity",
            field=models.FloatField(default=0, verbose_name="kinematic viscosity"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="analysis",
            name="material_condition",
            field=models.CharField(
                default="", max_length=255, verbose_name="material condition"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="analysis",
            name="pipe_diameter",
            field=models.FloatField(default=0, verbose_name="pipe diameter"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="analysis",
            name="pipe_length",
            field=models.FloatField(default=0, verbose_name="pipe length"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="analysis",
            name="pipe_material",
            field=models.CharField(
                default="", max_length=255, verbose_name="pipe material"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="analysis",
            name="volumetric_flow_rate",
            field=models.FloatField(default=0, verbose_name="volumetric flow rate"),
            preserve_default=False,
        ),
    ]
