# Generated by Django 3.2.2 on 2021-05-20 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0009_auto_20210520_0322"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysis",
            name="analysis_name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="analysis name"
            ),
        ),
    ]
