# Generated by Django 3.2.2 on 2021-05-27 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0010_alter_analysis_analysis_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PipeMaterial",
        ),
    ]
