# Generated by Django 3.2.2 on 2021-06-03 04:02

import analysis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0012_analysis_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='analysis_name',
            field=models.CharField(max_length=255, verbose_name='analysis name'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='density',
            field=models.FloatField(validators=[analysis.models.Analysis.validate_positive_float], verbose_name='density'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='kinematic_viscosity',
            field=models.FloatField(validators=[analysis.models.Analysis.validate_positive_float], verbose_name='kinematic viscosity'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='pipe_diameter',
            field=models.FloatField(validators=[analysis.models.Analysis.validate_positive_float], verbose_name='pipe diameter'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='pipe_length',
            field=models.FloatField(validators=[analysis.models.Analysis.validate_positive_float], verbose_name='pipe length'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='volumetric_flow_rate',
            field=models.FloatField(validators=[analysis.models.Analysis.validate_positive_float], verbose_name='volumetric flow rate'),
        ),
    ]
