# Generated by Django 3.2.2 on 2021-06-03 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0013_auto_20210603_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='reynolds_number',
            field=models.FloatField(blank=True, null=True, verbose_name='reynolds number'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='reynolds_number_regime',
            field=models.FloatField(blank=True, null=True, verbose_name='reynolds number'),
        ),
    ]
