# Generated by Django 3.2.2 on 2021-06-03 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0014_auto_20210603_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='reynolds_number_regime',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='reynolds number regime'),
        ),
    ]
