# Generated by Django 3.2.2 on 2021-05-13 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="analisys",
            options={"verbose_name_plural": "Analyses"},
        ),
    ]
