# Generated by Django 3.2.2 on 2021-05-13 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0002_alter_analisys_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Analisys",
            new_name="Analysis",
        ),
    ]
