# Generated by Django 3.2.2 on 2021-05-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0004_analysis_density"),
    ]

    operations = [
        migrations.CreateModel(
            name="PipeMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("material", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="analysis",
            name="kinematic_viscosity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="analysis",
            name="pipe_diameter",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="analysis",
            name="volumetric_flow_rate",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
